# This file is located at ~/rprofile-nice-dict.R
dict <- c(
  "Chat GPT user",
  "Love",
  "Dear",
  "Sweetheart",
  "Honey",
  "Babe",
  "Baby",
  "Darling",
  "Angel",
  "Sunshine",
  "Cutie",
  "Sweetie",
  "Pumpkin",
  "Lovebug",
  "Snugglebug",
  "Buttercup",
  "Cupcake",
  "Pumpkin Pie",
  "Muffin",
  "Peach",
  "Jellybean",
  "Love Muffin",
  "Babe Ruth",
  "Dearie",
  "Sugarplum",
  "Cherie",
  "Honey Bun",
  "My Love",
  "Sunshine Girl",
  "BabeAlert",
  "BabeO",
  "Snugglebear",
  "Cuddlebug",
  "Lovebird",
  "Cupcake Queen",
  "My Heart",
  "Princess",
  "Prince",
  "Cutiepie",
  "Pookie",
  "Pooh Bear",
  "Baby Doll",
  "Sweet Cheeks",
  "Sugar Bear",
  "Sugar Lips",
  "Muffin Top",
  "Little Star",
  "Sweetpea",
  "Snuggles",
  "Babycakes",
  "Snooky",
  "Love Bunny",
  "Honeybunch",
  "Snuggy",
  "Love Muffin",
  "Cupie",
  "My Treasure",
  "Baby Love",
  "Honey Bunny",
  "Sugar Plum",
  "Pumpkinhead",
  "Smiley",
  "Pumpkin Pie",
  "My Everything",
  "Beloved",
  "Teddy Bear",
  "Dollface",
  "Sweetums",
  "Cuppycake",
  "Sunshine Boy",
  "Babe Bear",
  "Bae",
  "My King",
  "Honey Lamb",
  "Snuggle Monster",
  "Jellybean",
  "Lovey",
  "Berry",
  "Honeybuns",
  "Cutie Patootie",
  "Pumpkin Spice",
  "Cuddle Bunny",
  "Love Pants",
  "My Angel",
  "Snugbug",
  "Pudding",
  "Snookie",
  "Heartbreaker",
  "Babe Face",
  "Love Potion",
  "Sugar Dumpling",
  "Snuggle Muffin",
  "Pookie Bear",
  "Twinkle Toes"
)
